
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
    lane :alpha do
        sync_code_signing(type: "appstore") 
  	build_app(scheme: "Alpha",
        project: "Login.xcodeproj",
        include_bitcode: false)
    end
end
