
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
    lane :alpha do
        match(
	app_identifier: "cz.cortex.StoreLocator",
	git_url: "https://Roman_Siro@bitbucket.org/Roman_Siro/login_certificates.git",
        username: "jiri.sulc@cortex.cz",
        readonly: true,
        type: "appstore"),  

  	build_app(scheme: "Alpha",
        project: "Login.xcodeproj",
        include_bitcode: false)
    end
end
